server:
  port: 8002
spring:
  application:
    name: aigou-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_user
    username: root
    password: root #1
mybatis-plus:
  mapper-locations: classpath:com/yh/aigou/mapper/*Mapper.xml
  type-aliases-package: com.yh.aigou.domain,com.yh.aigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true